import { Guest, AttendanceStatus } from './types';

const rawData = [
  { Fila: "2", Nombre: "Francisco", Apellido: "Myers", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "3", Nombre: "Devinica", Apellido: "De Myers", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "4", Nombre: "Lemuel", Apellido: "Soto", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "5", Nombre: "Aydana", Apellido: "De Soto", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "6", Nombre: "Anniel", Apellido: "Alonso", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "7", Nombre: "Betzaida", Apellido: "Bellorin", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "8", Nombre: "Carina", Apellido: "De Duque", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "9", Nombre: "Carlos", Apellido: "Quijada", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "10", Nombre: "Secia", Apellido: "De Quijada", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "11", Nombre: "Edinson", Apellido: "Salazar", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "12", Nombre: "Patricia", Apellido: "De Salazar", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "13", Nombre: "Eduardo", Apellido: "Salazar", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "14", Nombre: "Orlando", Apellido: "Soto", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "15", Nombre: "Nancy", Apellido: "De Soto", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "16", Nombre: "Misael", Apellido: "Medina", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "17", Nombre: "Thersy", Apellido: "De Medina", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "18", Nombre: "Maggui", Apellido: "Kufatti", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "19", Nombre: "Julián", Apellido: "Medina", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "20", Nombre: "Luisana", Apellido: "Mota", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "21", Nombre: "Luisanny", Apellido: "Mota", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "22", Nombre: "Norelis", Apellido: "Torres", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "23", Nombre: "Omaira", Apellido: "Afanador", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "24", Nombre: "Rosita", Apellido: "De Moncada", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "25", Nombre: "Ivana", Apellido: "Moncada", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "26", Nombre: "Vicenta", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "27", Nombre: "Douglas", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "28", Nombre: "Keyla", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "29", Nombre: "Zaidé", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "30", Nombre: "Sherly", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "31", Nombre: "Brianna", Apellido: "Becerra", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "32", Nombre: "Benjamín", Apellido: "Rodriguez", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "33", Nombre: "José", Apellido: "Díaz", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "34", Nombre: "Héctor", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "35", Nombre: "Sugeida", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "36", Nombre: "Antonio", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "37", Nombre: "Vanesa", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "38", Nombre: "Omar", Apellido: "Gonzalez", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "39", Nombre: "Dennis", Apellido: "Cedeño", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "40", Nombre: "Dany", Apellido: "Cedeño", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "41", Nombre: "Daniela", Apellido: "Cedeño", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "42", Nombre: "Hijo de Dennis", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "43", Nombre: "Edgar", Apellido: "Salazar", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "44", Nombre: "Joiner", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "45", Nombre: "Yedris", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "46", Nombre: "Elías", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "47", Nombre: "Uneidis", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "48", Nombre: "Sari", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "49", Nombre: "Esposo de Sari", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "50", Nombre: "Yadcidy", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "51", Nombre: "Alan", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "52", Nombre: "Richard", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "53", Nombre: "Yelitza", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "54", Nombre: "Ricardo", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "55", Nombre: "Reichel", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "56", Nombre: "María", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "57", Nombre: "José", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "58", Nombre: "Alirio", Apellido: "Moncada", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "59", Nombre: "Frank", Apellido: "Myers", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "60", Nombre: "Andrew", Apellido: "Myers", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "61", Nombre: "Abraham", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "62", Nombre: "Emanuel", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "63", Nombre: "Bryan", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "64", Nombre: "Alondra", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "65", Nombre: "Aranza", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "66", Nombre: "Darío", Apellido: "Medina", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "67", Nombre: "Nataly", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "68", Nombre: "Hijo de Ana Hidrogo", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "69", Nombre: "Hija de Ana Hidrogo", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "70", Nombre: "Hijo de Douglas y Keyla", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
  { Fila: "71", Nombre: "Hijo de Douglas y Keyla", Apellido: "", Dirección: "", Estado: "Bolívar", Ciudad: "Guayana", Iglesia: "Gracia Eterna", Teléfono: "", "Fecha Registro": "2025-10-16", Notas: "" },
];

const uniqueGuestsMap = new Map<string, typeof rawData[0]>();
rawData.forEach(item => {
    // Normalize by trimming whitespace and converting to lower case for a robust check
    const key = `${item.Nombre.trim().toLowerCase()}|${item.Apellido.trim().toLowerCase()}`;
    if (!uniqueGuestsMap.has(key)) {
        uniqueGuestsMap.set(key, item);
    }
});
const uniqueRawData = Array.from(uniqueGuestsMap.values());


export const initialGuestData: Guest[] = uniqueRawData.map(item => ({
  id: parseInt(item.Fila, 10),
  firstName: item.Nombre.trim(),
  lastName: item.Apellido.trim(),
  address: item.Dirección.trim(),
  state: item.Estado.trim(),
  city: item.Ciudad.trim(),
  church: item.Iglesia.trim(),
  phone: item.Teléfono.trim(),
  registrationDate: item['Fecha Registro'].trim(),
  notes: item.Notas.trim(),
  status: AttendanceStatus.PENDING,
  isPastor: false,
}));