[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
