services:
  # Backend API Service
  - type: web
    name: guest-manager-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci --include=dev && npx prisma generate && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api/v1/guests
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: api
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
